apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: operator-deployer-extrarole
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrole
      - clusterroles
      - clusterrolebindings
    verbs: ["get", "list"]