apiVersion: v1
kind: Pod
metadata:
  name: "${APP_INSTANCE_NAME}-tester"
  labels:
    app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
  annotations:
    marketplace.cloud.google.com/verification: test
spec:
  serviceAccount: ${APP_INSTANCE_NAME}-deployer-sa
  serviceAccountName: ${APP_INSTANCE_NAME}-deployer-sa
  hostNetwork: false
  containers:
    - name: tester
      image: "${testerImage}"
      imagePullPolicy: Always
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_INSTANCE_NAME
          value: ${APP_INSTANCE_NAME}
        - name: TESTER_TIMEOUT
          value: "900"
  restartPolicy: Never