properties:
  testerImage:
    type: string
    default: $REGISTRY/tester:$TAG
    x-google-property:
      type: IMAGE

  config_replicas:
    title: Number of elassandra nodes
    type: integer
    default: 2
    minimum: 1

  config_prometheus_enabled:
    title: Enabled Prometheus exporter
    type: boolean
    default: false

